### ISSUE TITLE
Not show scoreboard Kills

### ISSUE THREAD

**Issue by youngpvprock** [mbax/NameTags#12]
Hello, i found a bug of your plugin. If you the scoreboard for minecraft vanilla with this plugin on, the kills or all the variables don't works, always are in 0. 
You can test it making this:

/scoreboard objectives add Kills playerKillCount
/scoreboard objectives setdisplay belowName Kills

You will see that if you kill, the number is always in 0.. Please make compatible :l

**Comment by mbax** [comment]
This is a known problem. If you wish to use scoreboards, use a plugin that uses scoreboards for adding color to the username :)
