### ISSUE TITLE
/reload fails to update players nametag color

### ISSUE THREAD

**Issue by xeropresence** [mbax/NameTags#3]
Using 2.2 nametags and bperms v2.11.2

The following happens:
1)Update a groups perms(add or change nametag.color.blah)
2) do /perms reload
3) do /nametags reload

Outcome:
Everyone on the server has their color reset to whatever the default color is in the config file. If the default color in the file changes at the same time, ie before the nametag reload, the nametags will update properly.

**Comment by mbax** [comment]
Closing for oldness. If this is still an issue please reply and I'll reopen.
