### ISSUE TITLE
Nametags not initiating on all users.

### ISSUE THREAD

**Issue by mibby** [mbax/NameTags#4]
@mbax 

As discussed on IRC, some users within a rate of failure, are not receiving a colored nametag on initial deployment. 

Examples:

Premium group receives green nametag. 6 online, 2 do not have colored nametag.
Supporter group receives dark green nametag. 4 online, 1 does not have colored nametag.
VIP group receives gold nametag. 3 online, 1 does not have colored nametag.

A server restart typically fixes it for some users who did not have a nametag pre-restart, but other users, at random, lose their nametag they previously had, post-restart.

It seems to have nothing to do with character length and occurs at random, failing to deploy on some users. No errors in console at any point, plugins started up perfectly fine. Nametags and TagAPI do not output anything when the player's nametag is set to white instead of a color it is suppose to be.

TagAPI and Nametags config.yml. http://paste.ubuntu.com/6576936/

Nametags jenkins build 28.
TagAPI jenkins build 128.
http://ci.kitteh.org/

**Comment by mibby** [comment]
To add to the confusion, even with refreshAutomatically: true, users who did not get a nametag initially do not get refreshed. Stuck without a nametag until server restart.

**Comment by mbax** [comment]
Closing for oldness. If this is still an issue please reply and I'll reopen.
