### ISSUE TITLE
 Show exp level in Colored tag

### ISSUE THREAD

**Issue by mareksipos93** [mbax/NameTags#6]
Hello,

is it possible to add player's exp level before his nametag?

So if a player is administrator (tag [Admin] before nickname)
and server has level showing enabled, his tag will look like:
[Lv 8] [Admin] NickName

That would be epic and super useful.

Thanks for your time and if you have any questions, post them there please.

**Comment by mbax** [comment]
Nametags is a simple demonstration of changing tag. You can't put more than 16 characters in a tag, and so your idea cannot be done this way. The scoreboard system allows it but that isn't what nametags and tagapi are for

**Comment by mareksipos93** [comment]
And what if it will be shorten like
[Lv8-Admin] Nickname

So even if player has level > 100, there will still be 8 characters for the word itself
[Lv100-12345678]

I know that nametags are not for that, but well Minecraft is not for RPG and there are RPG servers, Minecraft was not made for minigames but there are lot of minigames, etc, etc... you thinks in a wrong way sir.

But I understand, you just don't want to do that and I accept it. I will just find a developer who can make this.

**Comment by mbax** [comment]
There are 16 character Minecraft usernames. The limit for name tags is 16 characters. ;)

There are plenty of plugins which already provide this functionality using the scoreboard system built into the game. Use one of them, don't say nonsense like "you just don't want to do that" when there is no feasible way to provide what you want using pure nametag manipulation.

**Comment by mareksipos93** [comment]
Oh I see, sorry for that, I didn't know that you are using ONLY TagAPI, I thought that your plugin can change scoreboard name if the length is over 16 characters, so players will don't have cutted names.

Do you have a reason, why you are limiting your plugin only to TagAPI? I think scoreboard system is much better choice for this purpose. Isn't it?
And you said that there are plenty of plugins which provide this functionality. Can you please post a link to one plugin I can add level to nametag with? Thanks a lot.

**Comment by mbax** [comment]
This plugin is the first TagAPI-using plugin (As TagAPI is also my plugin), and is a simple demonstration of it. :)

I'd suggest searching BukkitDev for one.
